package top.ntutn.starseasdk.proxy

import org.gradle.api.DefaultTask
import org.gradle.api.tasks.TaskAction

open class GenerateAliasFileTask: DefaultTask() {
    @TaskAction
    fun generate(packageName: String) {
        println("generating alias file.")

        var output = """
            package $packageName
            
            /**
             * generated by AliasProcessor
             * 这个类是对tg机器人框架starsea提供的最新版本API的alias
             * 用于固定包名，避免升级版本号后有一大片包名要改
             * have a nice day.
             */
             
        """.trimIndent()
        NewestApiInformation.newestApiClassNames.forEach {
            output += "\ntypedef ${getSimplifyName(it)} = $it\n"
        }

        println(output)
    }

    private fun getSimplifyName(fullName: String) = fullName.split(".").last()
}